server:
  port: ${SERVICE_PORT:8080}
spring:
  application:
    name: Zemoga Test
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://zemoga-test-db.crhpedy9xxto.us-east-1.rds.amazonaws.com:3306/portfolioDB}
    username: ${DATABASE_USERNAME:zemoga_test_db}
    password: ${DATABASE_PASSWORD:Zem0ga.101}
    hikari:
      connectionTimeout: ${PERSISTENCE_CONEC_TIMEOUT:30000}
      idleTimeout: ${PERSISTENCE_IDLE_TIMEOUT:600000}
      maxLifetime: ${PERSISTENCE_MAX_LIFETIME:1800000}
      maximumPoolSize: ${PERSISTENCE_MAX_POOL_SIZE:3}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
